### ISSUE TITLE
rust vendoring breaks meson build

### ISSUE THREAD

**Issue by dhellmann** [python-wheel-build/fromager#73]
```
**** handling build-system requirement meson>=0.63.3; python_version < "3.12" [('toplevel', <Requirement('llama-cpp-python==0.2.78')>, <Version('0.2.78')>), ('install', <Requirement('numpy>=1.20.0')>, <Version('1.26.4')>), ('build-system', <Requirement('meson-python<0.16.0,>=0.15.0')>, <Version('0.15.0')>)]
saved /work/bootstrap-output/sdists-repo/downloads/meson-1.4.1.tar.gz
new build-system dependency meson>=0.63.3; python_version < "3.12" resolves to 1.4.1
preparing source for meson>=0.63.3; python_version < "3.12" from /work/bootstrap-output/sdists-repo/downloads/meson-1.4.1.tar.gz
updating vendored rust dependencies in /work/bootstrap-output/work-dir/meson-1.4.1/meson-1.4.1
['cargo', 'vendor', '--manifest-path=/work/bootstrap-output/work-dir/meson-1.4.1/meson-1.4.1/test cases/rust/22 cargo subproject/subprojects/bar-rs/Cargo.toml', '--sync=/work/bootstrap-output/work-dir/meson-1.4.1/meson-1.4.1/test cases/rust/22 cargo subproject/subprojects/foo-rs/Cargo.toml', PosixPath('/work/bootstrap-output/work-dir/meson-1.4.1/meson-1.4.1/vendor')] failed with error: failed to parse manifest at `/work/bootstrap-output/work-dir/meson-1.4.1/meson-1.4.1/test cases/rust/22 cargo subproject/subprojects/bar-rs/Cargo.toml`

Caused by:
  TOML parse error at line 3, column 11
    |
  3 | version = "0.1"
    |           ^^^^^
  unexpected end of input while parsing minor version number

could not handle install dependency numpy>=1.20.0 for [('toplevel', <Requirement('llama-cpp-python==0.2.78')>, <Version('0.2.78')>)]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 182, in _handle_build_system_requirements
    resolved = handle_requirement(ctx, dep, 'build-system', why)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 102, in handle_requirement
    sdist_root_dir = sources.prepare_source(ctx, req, source_filename, resolved_version)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/sources.py", line 183, in prepare_source
    source_root_dir = preparer(ctx, req, source_filename, version)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/sources.py", line 194, in _default_prepare_source
    vendor_rust.vendor_rust(source_root_dir)
  File "/usr/local/lib/python3.11/site-packages/fromager/vendor_rust.py", line 107, in vendor_rust
    vendored = _cargo_vendor(manifests, project_dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/vendor_rust.py", line 35, in _cargo_vendor
    external_commands.run(args)
  File "/usr/local/lib/python3.11/site-packages/fromager/external_commands.py", line 44, in run
    raise subprocess.CalledProcessError(completed.returncode, cmd, output)
subprocess.CalledProcessError: Command '['cargo', 'vendor', '--manifest-path=/work/bootstrap-output/work-dir/meson-1.4.1/meson-1.4.1/test cases/rust/22 cargo subproject/subprojects/bar-rs/Cargo.toml', '--sync=/work/bootstrap-output/work-dir/meson-1.4.1/meson-1.4.1/test cases/rust/22 cargo subproject/subprojects/foo-rs/Cargo.toml', PosixPath('/work/bootstrap-output/work-dir/meson-1.4.1/meson-1.4.1/vendor')]' returned non-zero exit status 101.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 182, in _handle_build_system_requirements
    resolved = handle_requirement(ctx, dep, 'build-system', why)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 106, in handle_requirement
    build_system_dependencies = _handle_build_system_requirements(ctx, req, why, sdist_root_dir)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 184, in _handle_build_system_requirements
    raise ValueError(f'could not handle build-system dependency {dep} for {why}') from err
ValueError: could not handle build-system dependency meson>=0.63.3; python_version < "3.12" for [('toplevel', <Requirement('llama-cpp-python==0.2.78')>, <Version('0.2.78')>), ('install', <Requirement('numpy>=1.20.0')>, <Version('1.26.4')>), ('build-system', <Requirement('meson-python<0.16.0,>=0.15.0')>, <Version('0.15.0')>)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 155, in handle_requirement
    handle_requirement(ctx, dep, next_req_type, why)
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 106, in handle_requirement
    build_system_dependencies = _handle_build_system_requirements(ctx, req, why, sdist_root_dir)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 184, in _handle_build_system_requirements
    raise ValueError(f'could not handle build-system dependency {dep} for {why}') from err
ValueError: could not handle build-system dependency meson-python<0.16.0,>=0.15.0 for [('toplevel', <Requirement('llama-cpp-python==0.2.78')>, <Version('0.2.78')>), ('install', <Requirement('numpy>=1.20.0')>, <Version('1.26.4')>)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fromager/__main__.py", line 82, in invoke_main
    main(auto_envvar_prefix='FROMAGER')
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/commands/bootstrap.py", line 51, in bootstrap
    sdist.handle_requirement(wkctx, Requirement(toplevel))
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 157, in handle_requirement
    raise ValueError(f'could not handle {next_req_type} dependency {dep} for {why}') from err
ValueError: could not handle install dependency numpy>=1.20.0 for [('toplevel', <Requirement('llama-cpp-python==0.2.78')>, <Version('0.2.78')>)]
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 182, in _handle_build_system_requirements
    resolved = handle_requirement(ctx, dep, 'build-system', why)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 102, in handle_requirement
    sdist_root_dir = sources.prepare_source(ctx, req, source_filename, resolved_version)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/sources.py", line 183, in prepare_source
    source_root_dir = preparer(ctx, req, source_filename, version)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/sources.py", line 194, in _default_prepare_source
    vendor_rust.vendor_rust(source_root_dir)
  File "/usr/local/lib/python3.11/site-packages/fromager/vendor_rust.py", line 107, in vendor_rust
    vendored = _cargo_vendor(manifests, project_dir)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/vendor_rust.py", line 35, in _cargo_vendor
    external_commands.run(args)
  File "/usr/local/lib/python3.11/site-packages/fromager/external_commands.py", line 44, in run
    raise subprocess.CalledProcessError(completed.returncode, cmd, output)
subprocess.CalledProcessError: Command '['cargo', 'vendor', '--manifest-path=/work/bootstrap-output/work-dir/meson-1.4.1/meson-1.4.1/test cases/rust/22 cargo subproject/subprojects/bar-rs/Cargo.toml', '--sync=/work/bootstrap-output/work-dir/meson-1.4.1/meson-1.4.1/test cases/rust/22 cargo subproject/subprojects/foo-rs/Cargo.toml', PosixPath('/work/bootstrap-output/work-dir/meson-1.4.1/meson-1.4.1/vendor')]' returned non-zero exit status 101.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 182, in _handle_build_system_requirements
    resolved = handle_requirement(ctx, dep, 'build-system', why)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 106, in handle_requirement
    build_system_dependencies = _handle_build_system_requirements(ctx, req, why, sdist_root_dir)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 184, in _handle_build_system_requirements
    raise ValueError(f'could not handle build-system dependency {dep} for {why}') from err
ValueError: could not handle build-system dependency meson>=0.63.3; python_version < "3.12" for [('toplevel', <Requirement('llama-cpp-python==0.2.78')>, <Version('0.2.78')>), ('install', <Requirement('numpy>=1.20.0')>, <Version('1.26.4')>), ('build-system', <Requirement('meson-python<0.16.0,>=0.15.0')>, <Version('0.15.0')>)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 155, in handle_requirement
    handle_requirement(ctx, dep, next_req_type, why)
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 106, in handle_requirement
    build_system_dependencies = _handle_build_system_requirements(ctx, req, why, sdist_root_dir)
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 184, in _handle_build_system_requirements
    raise ValueError(f'could not handle build-system dependency {dep} for {why}') from err
ValueError: could not handle build-system dependency meson-python<0.16.0,>=0.15.0 for [('toplevel', <Requirement('llama-cpp-python==0.2.78')>, <Version('0.2.78')>), ('install', <Requirement('numpy>=1.20.0')>, <Version('1.26.4')>)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/bin/fromager", line 8, in <module>
    sys.exit(invoke_main())
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/__main__.py", line 82, in invoke_main
    main(auto_envvar_prefix='FROMAGER')
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/decorators.py", line 45, in new_func
    return f(get_current_context().obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/fromager/commands/bootstrap.py", line 51, in bootstrap
    sdist.handle_requirement(wkctx, Requirement(toplevel))
  File "/usr/local/lib/python3.11/site-packages/fromager/sdist.py", line 157, in handle_requirement
    raise ValueError(f'could not handle {next_req_type} dependency {dep} for {why}') from err
ValueError: could not handle install dependency numpy>=1.20.0 for [('toplevel', <Requirement('llama-cpp-python==0.2.78')>, <Version('0.2.78')>)]
```

**Comment by dhellmann** [comment]
@tiran do you have time to look at this? I don't know if we need better error handling, a different TOML lib, or if there's really an issue with the meson package.

**Comment by dhellmann** [comment]
The meson test suite is genuinely broken. I've worked around it in the customizations in our build environment.
